### ISSUE TITLE
Multiple dropbear users allowed

### ISSUE THREAD

**Issue by arzinekfh4** [borges1k6/ADMManager#1]
Limit to 1 concurrent dropbear connection doesn't work 
Multiple dropbear users are disconnected only when you manually press 16 (limiter).
It is not automatic.

**Comment by borges1k6** [comment]
Please see our official Telegram work, these problems have already been corrected and you have new and improved options, GET Tunnel, ShadowSockts, Sockts, SSL Tunnel among others. [https://t.me/admultimate]
